language: go
sudo: false

services:
  - docker

#addons:
#  apt:
#    sources:
#    packages:

#env:
#  global:

#before_install:

#before_script:

script:
  - make build
  - docker images
  - make test
  - make tgz

after_script:
  - pwd
  - ls -la
  - ls -laR bundles
