language: go
sudo: false # ony needed to run tests

services:
  - docker

matrix:
  fast_finish: true

before_script:
  - set -e

script:
  - make tgz
  - make manpages

after_script:
  - ls -laR bundles || true
  - ls -laR man || true

before_deploy:
  - cp bundles/latest/tgz/linux/386/docker-1.12.3.tgz "./docker-binary-linux-386-${TRAVIS_TAG}.tgz"
  - tar --numeric-owner --owner 0 -C "bundles/latest" -czf "docker-dynbinary-linux-386-${TRAVIS_TAG}.tgz" dynbinary-client dynbinary-daemon

deploy:
  provider: releases
  api_key:
    secure: "F32DvrsyalIhbymK6qmauYoeyAhMI/d7Kkj57YjB4EsipkngmXvDmppHB5kBTHwh+u/9fiWrruQsfGZTBjOoYjQKaohg/vfT8YPfPrUQlGA/xJ/510UouDmVTQyFDD2pJa2+MFlwQ9wvkEo2fXOUHRUu5P0LvgSMA5Uc6yryvqGdy5BdDabyPoXaY4bh41TZtGSbm/Zb6cvL0ZlkRjqzXHkubcu2yexTBBhGPtQTC3jSsA0TC8VWqOT6Pxu0GwxEZwI1PsGGF8cJpNTl/FgSfPhkWq+vvVARq+jDxe2a/rMAu4lI0dqWLUv9qAHXoxnS068j1BnHWRnmT6lOW0IWociAZdkkMcJL8o9DhodXr2Fy3/TsCw9K5ov+klGtnLT7u/WZTKppxRackggRm+d5He2nB6xZu0IOb01iBWCyVud/A+9ocx+GHnhR5V1QoB/VJUD0rbbCFWhjXIylMmvNgI9p2zWIFwmXEOGuomh55IqOnW/WleKEIHArZbT4eMXlWVZu8v1iq3rqDEd0IGkPtFgK2gAktqpdeEgj4HkCVQ0q0RTbnhhisc5d5kn8uTEobMjFl3taPwwCYNJS2Vp770sSsQop73hEAdE0nVDBABYpu5XcG2caPefsHvLO6rRr74FHgZNKnXzWfruaOHog77rNma/ugzlxvs5C8p3SyvE="
  file:
    - "docker-binary-linux-386-${TRAVIS_TAG}.tgz"
    - "docker-dynbinary-linux-386-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
#  overwrite: true
  on:
    tags: true
    repo: tslodki/docker
