language: go
sudo: false

services:
  - docker

#env:
#  global:

script:
  - make build
  - docker images
  - make binary
  - make cross
  - make tgz
  - make manpages

after_script:
  - pwd
  - ls -la
  - ls -laR bundles
