language: go
sudo: false # ony needed to run tests

services:
  - docker

matrix:
  fast_finish: true

before_script:
  - set -e

script:
  - make tgz
  - make manpages

after_script:
  - ls -laR bundles || true
  - ls -laR man || true

before_deploy:
  - cp bundles/latest/tgz/linux/386/docker-1.12.3.tgz "./docker-binary-linux-386-${TRAVIS_TAG}.tgz"
  - tar --numeric-owner --owner 0 -C "bundles/latest" -czf "docker-dynbinary-linux-386-${TRAVIS_TAG}.tgz" dynbinary-client dynbinary-daemon

deploy:
  provider: releases
  api_key: "e9e4700f6af44c3f0faf6198bdbf2b57b09c614f"
  file:
    - "docker-binary-linux-386-${TRAVIS_TAG}.tgz"
    - "docker-dynbinary-linux-386-${TRAVIS_TAG}.tgz"
  skip_cleanup: true
#  overwrite: true
  on:
    tags: true
    repo: tslodki/docker
